# Upon release package the extension in a zip file and add it to the Release artifacts
# The zip file can be used to publish a new version in the Chrome Extensions Marketplace
name: Create Extension Zip 

on:
  release:
    types:
      - created
  
jobs:
  create-and-upload-zip:
    name: Create and Upload ZIP
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Create the ZIP file
      - name: Create ZIP file
        run: |
          zip -r adyen-testcards-ext.zip ./ -x "./e2e/*" ".git/*" "./chrome-store-assets/*"

      # Upload the ZIP file to the release
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./adyen-testcards-ext.zip"]'
